//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public string Filepath { get; set; }
        public string Username { get; set; }
        public string Filesize { get; set; }
        public string Extension { get; set; }
        public string Datetime { get; set; }
    }
}
